package in.co.mark.webservices.iam.persistence.entities;

import java.util.Set;

import in.co.mark.common.persistence.EntityBase;
import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OneToOne;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Represents a <i>User</i> entity.
 * 
 * @author Rakesh Kumar
 */
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name = "users")
public class UserEObj extends EntityBase {
	/**
	 * <i>Primary key</i> of this entity. It will be auto-generated by the DB system
	 * when a new record is added.
	 */
	@Getter
	@Setter
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "IAM_UserIdSequence")
	@SequenceGenerator(name = "IAM_UserIdSequence", sequenceName = "IAM_UserIdSequence")
	private long id;

	@Getter
	@Setter
	@Column(name = "username", nullable = false)
	private String username;

	@Getter
	@Setter
	@Column(name = "email", unique = true, nullable = false)
	private String email;

	@Getter
	@Setter
	@Column(name = "initial")
	private String initial;

	@Getter
	@Setter
	@Column(name = "first_name")
	private String firstName;

	@Getter
	@Setter
	@Column(name = "middle_name")
	private String middleName;

	@Getter
	@Setter
	@Column(name = "last_name")
	private String lastName;

	@Getter
	@Setter
	@Column(name = "display_name")
	private String displayName;

	/**
	 * Gender of this user.
	 * <p>
	 * Possible values: <b>M</b> - Male, <b>F</b> - Female, <b>O</b> - Other, or
	 * <b>U</b> - Unknown
	 * </p>
	 */
	@Getter
	@Setter
	@Column(name = "gender", length = 1, nullable = true)
	private char gender;

	/** Date part of the date of birth of this user. */
	@Getter
	@Setter
	@Column(name = "dob_date")
	private int dobDate;

	/** Month part of the date of birth of this user. */
	@Getter
	@Setter
	@Column(name = "dob_month")
	private int dobMonth;

	/** Year part of the date of birth of this user. */
	@Getter
	@Setter
	@Column(name = "dob_year")
	private int dobYear;

	@Getter
	@Setter
	@Column(name = "avatar_uri")
	private String avatarUri;

	@Getter
	@OneToOne(mappedBy = "userEObj", optional = true, cascade = CascadeType.ALL, fetch = FetchType.LAZY)
	private UserCredentialEObj userCredEObj;

	@Getter
	@Setter
	@OneToMany(mappedBy = "userEObj")
	private Set<OrgUserEObj> orgUserEObjs;
}
