package in.co.mark.webservices.iam.domain.model;

import org.springframework.util.StringUtils;

import in.co.mark.common.domain.model.ModelBase;

/**
 * Represents a real world person as a {@code user} of the application.
 * 
 * @author Rakesh Kumar
 */
public class User extends ModelBase {
	/**
	 * ID which can uniquely identify this <i>user</i> in the system.
	 * <p>
	 * It should be auto-generated by the system while registering this user.
	 * </p>
	 */
	protected long id;

	/** Login username of this user. */
	protected String username;

	/** The primary email address of this user. */
	protected String email;

	/** Initial of this user. */
	protected String initial;

	/** First name of this user. */
	protected String firstName;

	/** Middle name of this user. */
	protected String middleName;

	/** Last name of this user. */
	protected String lastName;

	/** Display name or nick name of this user. */
	protected String displayName;

	/**
	 * Gender of this user.
	 * <p>
	 * Possible values: <b>M</b> - Male, <b>F</b> - Female, <b>O</b> - Other, or
	 * <b>U</b> - Unknown
	 * </p>
	 */
	protected char gender;

	/** Date part of the date-of-birth of this user. */
	protected int dobDate;

	/** Month part of the date-of-birth of this user. */
	protected int dobMonth;

	/** Year part of the date-of-birth of this user. */
	protected int dobYear;

	/** URI of the avatar image of this user. */
	protected String avatarUri;

	/** The default constructor of this class. */
	public User() {
	}

	/**
	 * Initializes {@code email}, {@code firstName}, and {@code lastName} properties
	 * of this instance. It also sets the given {@code email} as the login
	 * {@code username} of this instance.
	 * 
	 * @param email     The primary email address of this user
	 * @param firstName First name of this user
	 * @param lastName  Last name of this user
	 */
	public User(String email, String firstName, String lastName) {
		this(email, email, null, firstName, null, lastName, null, Character.MIN_VALUE, 1, 1, 1970, null);
	}

	/**
	 * Initializes {@code username}, {@code email}, {@code initial} ,
	 * {@code firstName}, {@code middleName}, {@code lastName}, {@code displayName},
	 * {@code gender}, {@code dobDate}, {@code dobMonth}, {@code dobYear}, and
	 * {@code avatarUri} properties of this instance.
	 * 
	 * @param username    Login username of this user. When {@code null}, the
	 *                    {@code email} value will be used as the login username.
	 * @param email       The primary email address of this user
	 * @param initial     Initial of this user
	 * @param firstName   First name of this user
	 * @param middleName  Middle name of this user
	 * @param lastName    Last name of this user
	 * @param displayName Display name or nick name of this user
	 * @param gender      Gender of this user. Possible values: <b>M</b> - Male,
	 *                    <b>F</b> - Female, or <b>O</b> - Other
	 * @param dobDate     Date part of the date-of-birth of this user
	 * @param dobMonth    Month part of the date-of-birth of this user
	 * @param dobYear     Year part of the date-of-birth of this user
	 * @param avatarUri   URI of avatar image of this user
	 */
	public User(String username, String email, String initial, String firstName, String middleName, String lastName,
			String displayName, char gender, int dobDate, int dobMonth, int dobYear, String avatarUri) {
		this.email = email;
		this.username = StringUtils.hasText(username) ? username.trim() : email;
		this.initial = initial;
		this.firstName = firstName;
		this.middleName = middleName;
		this.lastName = lastName;
		this.displayName = displayName;
		this.gender = gender;
		this.dobDate = dobDate;
		this.dobMonth = dobMonth;
		this.dobYear = dobYear;
		this.avatarUri = avatarUri;
	}

	/**
	 * Initializes all properties of this instance.
	 * 
	 * @param id            ID of this user
	 * @param username      Login username of this user. When {@code null}, the
	 *                      {@code email} value will be used as the login username.
	 * @param email         The primary email address of this user
	 * @param initial       Initial of this user
	 * @param firstName     First name of this user
	 * @param middleName    Middle name of this user
	 * @param lastName      Last name of this user
	 * @param displayName   Display name or nick name of this user
	 * @param gender        Gender of this user. Possible values: <b>M</b> - Male,
	 *                      <b>F</b> - Female, or <b>O</b> - Other
	 * @param dobDate       Date part of the date-of-birth of this user
	 * @param dobMonth      Month part of the date-of-birth of this user
	 * @param dobYear       Year part of the date-of-birth of this user
	 * @param avatarUri     URI of avatar image of the user
	 * @param createdOn     A timestamp indicating when this user was created
	 * @param lastUpdatedOn A timestamp indicating when this user was last updated
	 */
	public User(long id, String username, String email, String initial, String firstName, String middleName,
			String lastName, String displayName, char gender, int dobDate, int dobMonth, int dobYear, String avatarUri,
			long createdOn, long lastUpdatedOn) {
		this(email, username, initial, firstName, middleName, lastName, displayName, gender, dobDate, dobMonth, dobYear,
				avatarUri);
		this.id = id;
		this.createdOn = createdOn;
		this.lastUpdatedOn = lastUpdatedOn;
	}

	/**
	 * Gets the user {@code id}.
	 * 
	 * @return User {@code id}
	 */
	public long getId() {
		return id;
	}

	/**
	 * Sets the given {@code id} as user ID of this instance.
	 * 
	 * @param id A {@code long} value to set as user ID
	 */
	public void setId(long id) {
		this.id = id;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getInitial() {
		return initial;
	}

	public void setInitial(String initial) {
		this.initial = initial;
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getMiddleName() {
		return middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getDisplayName() {
		return displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

	public char getGender() {
		return gender;
	}

	/**
	 * Gets {@code gender} of this user as human readable string.
	 * 
	 * 
	 * @return "Male" for {@code gender} value <b>M</b>, "Female" for <b>F</b>,
	 *         "Other" for <b>O</b>, and an empty string otherwise
	 */
	public String getGenderString() {
		switch (gender) {
		case 'M':
		case 'm':
			return "Male";
		case 'F':
		case 'f':
			return "Female";
		case 'O':
		case 'o':
			return "Other";
		default:
			return "Unknown";
		}
	}

	public void setGender(char gender) {
		this.gender = gender;
	}

	public int getDobDate() {
		return dobDate;
	}

	public void setDobDate(int dobDate) {
		this.dobDate = dobDate;
	}

	public int getDobMonth() {
		return dobMonth;
	}

	public void setDobMonth(int dobMonth) {
		this.dobMonth = dobMonth;
	}

	public int getDobYear() {
		return dobYear;
	}

	public void setDobYear(int dobYear) {
		this.dobYear = dobYear;
	}

	public String getAvatarUri() {
		return avatarUri;
	}

	public void setAvatarUri(String avatarUri) {
		this.avatarUri = avatarUri;
	}
}
