package in.co.mark.webservices.iam.gateway.dto;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * @author Rakesh Kumar
 */
@AllArgsConstructor
@NoArgsConstructor
public class UserRequestDTO {
	/**
	 * <i>Primary key</i> of the respective entity. Set it to {@code null} for new
	 * user registrations, as it would be auto-generated by the system when a new
	 * record is added.
	 */
	@Getter
	@Setter
	private long userId;

	/**
	 * Login usernname of this user. When not set explicitly, the primary
	 * {@code email} of this user will be used as the login username.
	 */
	@Getter
	@Setter
	private String username;

	/** Primary email address of this user. */
	@Getter
	@Setter
	private String email;

	/** Login password of this user. */
	@Getter
	@Setter
	private String password;

	/** Initial part of the name of this user. */
	@Getter
	@Setter
	private String initial;

	/** First name of this user. */
	@Getter
	@Setter
	private String firstName;

	/** Middle name of this user. */
	@Getter
	@Setter
	private String middleName;

	/** Last name of this user. */
	@Getter
	@Setter
	private String lastName;

	/** Display name or nick name of this user. */
	@Getter
	@Setter
	private String displayName;

	/**
	 * Gender of this user.
	 * <p>
	 * Possible values: <b>M</b> - Male, <b>F</b> - Female, <b>O</b> - Other, or
	 * <b>U</b> - Unknown
	 * </p>
	 * When not set explicitly, the system may return <b>U</b> - for Unknown.
	 */
	@Getter
	@Setter
	private char gender;

	/** Date part of the date-of-birth of this user. */
	@Getter
	@Setter
	private int dobDate;

	/** Month part of the date-of-birth of this user. */
	@Getter
	@Setter
	private int dobMonth;

	/** Year part of the date-of-birth of this user. */
	@Getter
	@Setter
	private int dobYear;
}
