package in.co.mark.webservices.iam.domain.model;

/**
 * Represents a login {@code credential}.
 * 
 * @author Rakesh Kumar
 */
public class LoginCredential {
	/**
	 * This ID will be generated by the system on successful registration of a user,
	 * and it can be used to uniquely identify the user in the system.
	 */
	private long id;
	private String username;
	private String password;
	private long createdOn;
	private long lastUpdatedOn;

	/**
	 * Initializes {@code username} and {@code password} properties of this class
	 * with the given parameter values
	 * 
	 * @param username Username to login to the service
	 * @param password Password to login to the service
	 */
	public LoginCredential(String username, String password) {
		this.username = username;
		this.password = password;
	}

	/**
	 * Initializes {@code username} and {@code password} properties of this class
	 * with the given parameter values
	 * 
	 * @param id            ID of this login credential
	 * @param username      Username to login to the service
	 * @param password      Password to login to the service
	 * @param createdOn     A timestamp indicating when this login credential was
	 *                      created
	 * @param lastUpdatedOn A timestamp indicating when this login credential was
	 *                      last updated
	 */
	public LoginCredential(long id, String username, String password, long createdOn, long lastUpdatedOn) {
		this.id = id;
		this.username = username;
		this.password = password;
		this.createdOn = createdOn;
		this.lastUpdatedOn = lastUpdatedOn;
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public long getCreatedOn() {
		return createdOn;
	}

	public void setCreatedOn(long createdOn) {
		this.createdOn = createdOn;
	}

	public long getLastUpdatedOn() {
		return lastUpdatedOn;
	}

	public void setLastUpdatedOn(long lastUpdatedOn) {
		this.lastUpdatedOn = lastUpdatedOn;
	}
}
