package in.co.mark.webservices.iam.domain.model;

import in.co.mark.common.domain.model.ModelBase;
import in.co.mark.common.persistence.util.EntityActiveStatus;

/**
 * Represents an {@code organization}.
 * 
 * @author Rakesh Kumar
 */
public class Organization extends ModelBase {
	/**
	 * ID which can uniquely identify this <i>organization</i> in the system.
	 * <p>
	 * It should be auto-generated by the system while registering this user.
	 * </p>
	 */
	private long id;

	/**
	 * ID of the <i>Super Admin</i> user of this organization.
	 * <p>
	 * An organization can have one and only one <i>Super Admin</i> user, and that
	 * user will have the maximum privileges in the organization.
	 * </p>
	 */
	private long superAdminId;

	/** Name of the organization. */
	private String orgName;

	/** Description of the organization. */
	private String desc;

	/** ID of the parent organization, if any. */
	private long parentOrgId;

	/** Status of this organization in the system. */
	private EntityActiveStatus status;

	/** The default constructor of this class. */
	public Organization() {
	}

	/**
	 * Initializes {@code id}, {@code superAdminId}, {@code orgName}, {@code desc},
	 * {@code parentOrgId}, and {@code status} properties of this class.
	 * 
	 * @param id           DB ID of this instance
	 * @param superAdminId ID of the <i>Super Admin</i> of this organization
	 * @param orgName      Name of this organization
	 * @param desc         A short description
	 * @param parentOrgId  ID of the parent organization, if any
	 * @param status       Status of this organization
	 */
	public Organization(long id, long superAdminId, String orgName, String desc, long parentOrgId,
			EntityActiveStatus status) {
		this.id = id;
		this.superAdminId = superAdminId;
		this.orgName = orgName;
		this.desc = desc;
		this.parentOrgId = parentOrgId;
		this.status = status;
	}

	/**
	 * Initializes all properties of this class.
	 * 
	 * @param id            DB ID of this instance
	 * @param superAdminId  ID of the <i>Super Admin</i> of this organization
	 * @param orgName       Name of this organization
	 * @param desc          A short description
	 * @param parentOrgId   ID of the parent organization, if any
	 * @param status        Status of this organization
	 * @param createdOn     A timestamp indicating when this user was created
	 * @param lastUpdatedOn A timestamp indicating when this user was last updated
	 */
	public Organization(long id, long superAdminId, String orgName, String desc, long parentOrgId,
			EntityActiveStatus status, long createdOn, long lastUpdatedOn) {
		super(createdOn, lastUpdatedOn);
		this.id = id;
		this.superAdminId = superAdminId;
		this.orgName = orgName;
		this.desc = desc;
		this.parentOrgId = parentOrgId;
		this.status = status;
	}

	/**
	 * Gets the {@code id} of this instance.
	 * 
	 * @return {@code id} of this instance
	 */
	public long getId() {
		return id;
	}

	/**
	 * Sets the {@code id} to this instance.
	 * <p>
	 * Being <i>primary key</i> of the respective entity, the {@code id} should be a
	 * value auto-generated by the DB system when a new record is added.
	 * </p>
	 * 
	 * @param id <i>Primary key</i> of the respective entity
	 */
	public void setId(long id) {
		this.id = id;
	}

	/**
	 * Gets the {@code id} of the <i>Super Admin</i> user of this organization.
	 * <p>
	 * Note that an organization can have one and only one <i>Super Admin</i> user,
	 * and that user will have the maximum privileges in the organization.
	 * </p>
	 * 
	 * @return ID of the <i>Super Admin</i> user
	 */
	public long getSuperAdminId() {
		return superAdminId;
	}

	/**
	 * Sets the {@code superAdminId} to this organization.
	 * <p>
	 * Note that an organization can have one and only one <i>Super Admin</i> user,
	 * and that user will have the maximum privileges in the organization.
	 * </p>
	 * 
	 * @param superAdminId ID of the <i>Super Admin</i> user of this organization
	 */
	public void setSuperAdminId(long superAdminId) {
		this.superAdminId = superAdminId;
	}

	/**
	 * Gets the name of this organization.
	 * 
	 * @return Name of this organization
	 */
	public String getOrgName() {
		return orgName;
	}

	/**
	 * Sets a name to this organization.
	 * 
	 * @param orgName Name of this organization. It must be unique.
	 */
	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}

	/**
	 * Gets the description of this organization.
	 * 
	 * @return Description of this organization
	 */
	public String getDesc() {
		return desc;
	}

	/**
	 * Sets a description to this organization.
	 * 
	 * @param desc Description of this organization
	 */
	public void setDesc(String desc) {
		this.desc = desc;
	}

	/**
	 * Gets the {@code id} of the parent organization, if any. It can be
	 * {@code null} when there is no parent organization registered.
	 * 
	 * @return ID of the parent organization
	 */
	public long getParentOrgId() {
		return parentOrgId;
	}

	/**
	 * Sets the {@code parentOrgId} to this organization. It can be {@code null}
	 * indicating no parent organization registered.
	 * 
	 * @param parentOrgId ID of the parent organization (can be {@code null})
	 */
	public void setParentOrgId(long parentOrgId) {
		this.parentOrgId = parentOrgId;
	}

	/**
	 * Gets the status of this organization in the system
	 * 
	 * @return Status of this organization in the system
	 */
	public EntityActiveStatus getStatus() {
		return status;
	}

	/**
	 * Sets an status to this organization in the system
	 * 
	 * @param status {@link EntityActiveStatus} indicating the status of this
	 *               organization in the system
	 */
	public void setStatus(EntityActiveStatus status) {
		this.status = status;
	}
}
