package in.co.mark.webservices.iam.domain.model;

/**
 * Represents a {@code user} of the application
 * 
 * @author Rakesh Kumar
 */
public class User {
	/**
	 * This ID will be generated by the system on successful registration of a user,
	 * and it can be used to uniquely identify the user in the system.
	 */
	private long id;
	private String email;
	private String displayName;
	private String avatarUri;
	private long createdOn;
	private long lastUpdatedOn;

	/**
	 * Initializes {@code displayName}, {@code email}, and {@code avatarUri}
	 * properties of this class with given parameter values
	 * 
	 * @param email       Email address of the user. Also used as the login username
	 * @param displayName Display name (or full name) of the user
	 * @param avatarUri   URI of avatar image of the user
	 */
	public User(String email, String displayName, String avatarUri) {
		this.email = email;
		this.displayName = displayName;
		this.avatarUri = avatarUri;
	}

	/**
	 * Initializes {@code id}, {@code email}, {@code displayName},
	 * {@code avatarUri}, {@code createdOn}, and {@code lastUpdatedOn} properties of
	 * this class with given parameter values
	 * 
	 * @param id            ID of this contact
	 * @param email         Email address of the user. Also used as the login
	 *                      username
	 * @param displayName   Display name (or full name) of the user
	 * @param avatarUri     URI of avatar image of the user
	 * @param createdOn     A timestamp indicating when this contact was created
	 * @param lastUpdatedOn A timestamp indicating when this contact was last
	 *                      updated
	 */
	public User(long id, String email, String displayName, String avatarUri, long createdOn, long lastUpdatedOn) {
		this.id = id;
		this.email = email;
		this.displayName = displayName;
		this.avatarUri = avatarUri;
		this.createdOn = createdOn;
		this.lastUpdatedOn = lastUpdatedOn;
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getDisplayName() {
		return displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

	public String getAvatarUri() {
		return avatarUri;
	}

	public void setAvatarUri(String avatarUri) {
		this.avatarUri = avatarUri;
	}

	public long getCreatedOn() {
		return createdOn;
	}

	public void setCreatedOn(long createdOn) {
		this.createdOn = createdOn;
	}

	public long getLastUpdatedOn() {
		return lastUpdatedOn;
	}

	public void setLastUpdatedOn(long lastUpdatedOn) {
		this.lastUpdatedOn = lastUpdatedOn;
	}
}
