package in.co.mark.webservices.iam.domain.model;

/**
 * Represents a real world person as a {@code user} of the application.
 * 
 * @author Rakesh Kumar
 */
public class User {
	/**
	 * This ID will be generated by the system on successful registration of a user,
	 * and it can be used to uniquely identify the user in the system.
	 */
	private long id;

	private String initial;
	private String firstName;
	private String middleName;
	private String lastName;
	private String displayName;
	private String gender;
	private int dobDate;
	private int dobMonth;
	private int dobYear;

	/**
	 * The primary email address of the user
	 */
	private String email;
	private String avatarUri;

	private long createdOn;
	private long lastUpdatedOn;

	/**
	 * Initializes {@code email}, {@code firstName}, {@code middleName}, and
	 * {@code lastName} properties of this class with the given parameter values
	 * 
	 * @param email      The primary email address of the user
	 * @param firstName  First name of the user
	 * @param middleName Middle name of the user
	 * @param lastName   Last name of the user
	 */
	public User(String email, String firstName, String middleName, String lastName) {
		this.email = email;
		this.firstName = firstName;
		this.middleName = middleName;
		this.lastName = lastName;
	}

	/**
	 * Initializes {@code id}, {@code email}, {@code firstName}, {@code middleName},
	 * {@code lastName}, {@code avatarUri}, {@code createdOn}, and
	 * {@code lastUpdatedOn} properties of this class with the given parameter
	 * values
	 * 
	 * @param id            ID of this user
	 * @param email         The primary email address of the user
	 * @param firstName     First name of the user
	 * @param middleName    Middle name of the user
	 * @param lastName      Last name of the user
	 * @param avatarUri     URI of avatar image of the user
	 * @param createdOn     A timestamp indicating when this user was created
	 * @param lastUpdatedOn A timestamp indicating when this user was last updated
	 */
	public User(long id, String email, String firstName, String middleName, String lastName, long createdOn,
			long lastUpdatedOn) {
		this.id = id;
		this.email = email;
		this.firstName = firstName;
		this.middleName = middleName;
		this.lastName = lastName;
		this.createdOn = createdOn;
		this.lastUpdatedOn = lastUpdatedOn;
	}

	/**
	 * To get the ID of this user.
	 * <p>
	 * This ID would have been generated by the system after successful registration
	 * of a user, and could be used to uniquely identify the user in the system.
	 * </p>
	 * 
	 * @return {@code id} of this user
	 */
	public long getId() {
		return id;
	}

	/**
	 * To set the ID of this user.
	 * <p>
	 * The {@code id} being <i>primary key</i> of this entity, it should, ideally,
	 * be set by the DB system on successful creation of the respective record.
	 * </p>
	 * 
	 * @param id ID of this user
	 */
	public void setId(long id) {
		this.id = id;
	}

	public String getInitial() {
		return initial;
	}

	public void setInitial(String initial) {
		this.initial = initial;
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getMiddleName() {
		return middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getDisplayName() {
		return displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

	public String getGender() {
		return gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public int getDobDate() {
		return dobDate;
	}

	public void setDobDate(int dobDate) {
		this.dobDate = dobDate;
	}

	public int getDobMonth() {
		return dobMonth;
	}

	public void setDobMonth(int dobMonth) {
		this.dobMonth = dobMonth;
	}

	public int getDobYear() {
		return dobYear;
	}

	public void setDobYear(int dobYear) {
		this.dobYear = dobYear;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getAvatarUri() {
		return avatarUri;
	}

	public void setAvatarUri(String avatarUri) {
		this.avatarUri = avatarUri;
	}

	public long getCreatedOn() {
		return createdOn;
	}

	public void setCreatedOn(long createdOn) {
		this.createdOn = createdOn;
	}

	public long getLastUpdatedOn() {
		return lastUpdatedOn;
	}

	public void setLastUpdatedOn(long lastUpdatedOn) {
		this.lastUpdatedOn = lastUpdatedOn;
	}
}
