package in.co.mark.webservices.iam.persistence.entities;

import java.util.Set;

import in.co.mark.common.persistence.EntityBase;
import in.co.mark.common.persistence.util.EntityActiveStatus;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Represents an <i>Organization</i> entity.
 * 
 * @author Rakesh Kumar
 */
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name = "organizations")
public class OrganizationEObj extends EntityBase {
	/**
	 * <i>Primary key</i> of this entity. It will be auto-generated by the DB system
	 * when a new record is added.
	 */
	@Getter
	@Setter
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "IAM_OrgIdSequence")
	@SequenceGenerator(name = "IAM_OrgIdSequence", sequenceName = "IAM_OrgIdSequence")
	private long id;

	@Getter
	@Setter
	@Column(name = "super_admin_id")
	private long superAdminId;

	@Getter
	@Setter
	@Column(name = "org_name")
	private String orgName;

	@Getter
	@Setter
	@Column(name = "description")
	private String desc;

	/** ID of the parent organization, if any. */
	@Getter
	@Setter
	@Column(name = "parent_org_id")
	private long parentOrgId;

	@Getter
	@Setter
	@Column(name = "status")
	private EntityActiveStatus status;

	@Getter
	@Setter
	@OneToMany(mappedBy = "organizationEObj")
	private Set<OrgUserEObj> orgUserEObjs;
}
