package in.co.mark.webservices.iam.persistence.entities;

import in.co.mark.common.persistence.EntityBase;
import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToOne;
import jakarta.persistence.SequenceGenerator;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@AllArgsConstructor
@NoArgsConstructor
@Entity(name = "users")
public class UserEObj extends EntityBase {
	/**
	 * The <i>primary key</i> of this entity. It will be auto-generated by the DB
	 * system on successful creation of the respective record.
	 */
	@Getter
	@Setter
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "IAM_UserIdSequence")
	@SequenceGenerator(name = "IAM_UserIdSequence", sequenceName = "IAM_UserIdSequence")
	private long id;

	@Getter
	@Setter
	@Column(name = "email", unique = true, nullable = false)
	private String email;

	@Getter
	@Setter
	@Column(name = "initial")
	private String initial;

	@Getter
	@Setter
	@Column(name = "first_name")
	private String firstName;

	@Getter
	@Setter
	@Column(name = "middle_name")
	private String middleName;

	@Getter
	@Setter
	@Column(name = "last_name")
	private String lastName;
	@Getter
	@Setter
	@Column(name = "display_name")
	private String displayName;

	/** Possible values: <b>M</b> - Male, <b>F</b> - Female, or <b>O</b> - Other */
	@Getter
	@Setter
	@Column(name = "gender", length = 1)
	private char gender;

	/** Date part of the date of birth of this user */
	@Getter
	@Setter
	@Column(name = "dob_date")
	private int dobDate;

	/** Month part of the date of birth of this user */
	@Getter
	@Setter
	@Column(name = "dob_month")
	private int dobMonth;

	/** Year part of the date of birth of this user */
	@Getter
	@Setter
	@Column(name = "dob_year")
	private int dobYear;

	@Getter
	@Setter
	@Column(name = "avatar_uri")
	private String avatarUri;

	@Getter
	@OneToOne(mappedBy = "userEObj", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
	private UserCredentialEObj userCredEObj;

	public void setUserCredEObj(UserCredentialEObj userCredEObj) {
		this.userCredEObj = userCredEObj;
		if (userCredEObj != null) {
			userCredEObj.setUserEObj(this); // Establishes bidirectional relationship
		}
	}
}
