server.port=8080

spring.thymeleaf.cache=false
spring.thymeleaf.enabled=true 
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

spring.application.name=MaRK Web Service

spring.datasource.url=jdbc:postgresql://localhost:5432/webservices_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# Hibernate properties
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# GitHub OAuth2 Configurations
# GitHub Client ID: "82cec14d758ec4219c8a"
# GitHub Client Secret: "7192ef9da29b597f33bf95201c0a2df22718a763"
# GitHub
#spring.security.oauth2.client.registration.github.client-id=82cec14d758ec4219c8a
#spring.security.oauth2.client.registration.github.client-secret=7192ef9da29b597f33bf95201c0a2df22718a763