package in.co.mark.webservices.contacts.persistence.entities;

import in.co.mark.common.persistence.OwnerSpecificEntityBase;
import in.co.mark.common.persistence.util.EntityActiveStatus;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.SequenceGenerator;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@AllArgsConstructor
@NoArgsConstructor
@Entity(name = "contact_identifiers")
public class ContactIdentifierEObj extends OwnerSpecificEntityBase {
	/**
	 * The <i>primary key</i> of this entity. It will be auto-generated by the DB
	 * system on successful creation of the respective record.
	 */
	@Getter
	@Setter
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "ContactEmailIdSequence")
	@SequenceGenerator(name = "ContactEmailIdSequence", sequenceName = "ContactEmailIdSequence")
	private long id;

	@Getter
	@Setter
	@Column(name = "contact_id")
	private long contactId;

	@Getter
	@Setter
	@Column(name = "identifier_type_id")
	private long identifierTypeId;

	@Getter
	@Setter
	@Column(name = "identifier_value")
	private String identifierValue;

	@Getter
	@Setter
	@Column(name = "description")
	private String desc;

	@Getter
	@Setter
	@Column(name = "issue_location")
	private String issueLocation;

	@Getter
	@Setter
	@Column(name = "issue_date")
	private long issueDate;

	@Getter
	@Setter
	@Column(name = "expiry_date")
	private long expiryDate;

	@Getter
	@Setter
	@Column(name = "status")
	private EntityActiveStatus Status;
}
