package in.co.mark.webservices.contacts.persistence.entities;

import java.time.Instant;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.SequenceGenerator;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@AllArgsConstructor
@NoArgsConstructor
@Entity(name = "contacts")
public class ContactEObj {
	/**
	 * The <i>primary key</i> of this entity. It will be auto-generated by the DB
	 * system on successful creation of the respective record.
	 */
	@Getter
	@Setter
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "ContactIdSequence")
	@SequenceGenerator(name = "ContactIdSequence", sequenceName = "ContactIdSequence")
	private long id;
	@Getter
	@Setter
	@Column(name = "name_prefix_id")
	private int namePrefixId;

	@Getter
	@Setter
	@Column(name = "initial")
	private String initial;
	@Getter
	@Setter
	@Column(name = "first_name")
	private String firstName;

	@Getter
	@Setter
	@Column(name = "middle_name")
	private String middleName;

	@Getter
	@Setter
	@Column(name = "last_name")
	private String lastName;

	@Getter
	@Setter
	@Column(name = "nick_name")
	private String nickName;

	@Getter
	@Setter
	@Column(name = "name_suffix_id")
	private int nameSuffixId;

	@Getter
	@Setter
	@Column(name = "gender")
	private String gender;

	@Getter
	@Setter
	@Column(name = "dob_date")
	private int dobDate;

	@Getter
	@Setter
	@Column(name = "dob_month")
	private int dobMonth;

	@Getter
	@Setter
	@Column(name = "dob_year")
	private int dobYear;

	@Getter
	@Setter
	@Column(name = "avatar_uri")
	private String avatarUri;

	@Getter
	@Setter
	@Column(name = "marital_status_id")
	private int maritalStatusId;
	@Getter
	@Setter
	@Column(name = "marriage_date")
	private int marriageDate;

	@Getter
	@Setter
	@Column(name = "marriage_month")
	private int marriageMonth;

	@Getter
	@Setter
	@Column(name = "marriage_year")
	private int marriageYear;

	@Getter
	@Setter
	@Column(name = "spouse_contact_id")
	private long spouseContactId;

	@Getter
	@Setter
	@Column(name = "spouse_name")
	private String spouseName;

	@Getter
	@Setter
	@Column(name = "is_fav")
	private boolean isFav;

	@Getter
	@Setter
	@Column(name = "created_on", nullable = false)
	private long createdOn;

	@Getter
	@Setter
	@Column(name = "last_updated_on", nullable = false)
	private long lastUpdatedOn;

	@PrePersist
	public void prePersist() {
		long currTimeMilli = Instant.now().toEpochMilli();
		createdOn = currTimeMilli;
		lastUpdatedOn = currTimeMilli;
	}

	@PreUpdate
	public void preUpdate() {
		lastUpdatedOn = Instant.now().toEpochMilli();
	}
}
