package in.co.mark.webservices.contacts.domain.model;

public class AddressType {
	/**
	 * The <i>primary key</i> of this entity. It will be generated by the DB system
	 * on successful creation of the respective record.
	 */
	private long id;
	private String type;
	private String desc;
	private long createdOn;
	private long lastUpdatedOn;

	/**
	 * Default constructor
	 */
	public AddressType() {
	}

	/**
	 * Initializes {@code type} and {@code desc} properties of this instance
	 * 
	 * @param type Type of this address type
	 * @param desc Description of this address type
	 */
	public AddressType(String type, String desc) {
		this.type = type;
		this.desc = desc;
	}

	/**
	 * Constructor with all fields
	 * 
	 * @param id            ID of this address type
	 * @param type          Type of this address type
	 * @param desc          Description of this address type
	 * @param createdOn     A timestamp indicating when this address type was
	 *                      created
	 * @param lastUpdatedOn A timestamp indicating when this address type was last
	 *                      updated
	 */
	public AddressType(long id, String type, String desc, long createdOn, long lastUpdatedOn) {
		this.id = id;
		this.type = type;
		this.desc = desc;
		this.createdOn = createdOn;
		this.lastUpdatedOn = lastUpdatedOn;
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getDesc() {
		return desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

	public long getCreatedOn() {
		return createdOn;
	}

	public void setCreatedOn(long createdOn) {
		this.createdOn = createdOn;
	}

	public long getLastUpdatedOn() {
		return lastUpdatedOn;
	}

	public void setLastUpdatedOn(long lastUpdatedOn) {
		this.lastUpdatedOn = lastUpdatedOn;
	}
}
