package in.co.mark.webservices.contacts.domain.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import in.co.mark.common.domain.model.OwnerSpecificModelBase;

public class AddressType extends OwnerSpecificModelBase {
	/**
	 * The <i>primary key</i> of this entity. It will be generated by the DB system
	 * on successful creation of the respective record.
	 */
	private long id;
	private boolean isOwnerOrg;
	private String addressType;
	private String desc;

	/**
	 * Default constructor
	 */
	public AddressType() {
	}

	/**
	 * Initializes {@code ownerId}, {@code addressType} and {@code desc} properties
	 * of this instance
	 * 
	 * @param ownerId     ID of the owner - can be a user or an organization
	 * @param addressType Type of this address type
	 * @param desc        Description of this address type
	 */
	public AddressType(long ownerId, String addressType, String desc) {
		super(ownerId);
		this.addressType = addressType;
		this.desc = desc;
	}

	/**
	 * Initializes {@code ownerId}, {@code addressType} and {@code desc} properties
	 * of this instance
	 * 
	 * @param ownerId     ID of the owner - can be a user or an organization
	 * @param isOwnerOrg  Set to {@code true}, if the owner of this instance
	 *                    represented by {@code ownerId} is an organization;
	 *                    otherwise, {@code false}
	 * @param addressType Type of this address type
	 * @param desc        Description of this address type
	 */
	public AddressType(long ownerId, boolean isOwnerOrg, String addressType, String desc) {
		super(ownerId);
		this.isOwnerOrg = isOwnerOrg;
		this.addressType = addressType;
		this.desc = desc;
	}

	/**
	 * Constructor with all fields
	 * 
	 * @param id            ID of this address type
	 * @param ownerId       ID of the owner - can be a user or an organization
	 * @param isOwnerOrg    Set to {@code true}, if the owner of this instance
	 *                      represented by {@code ownerId} is an organization;
	 *                      otherwise, {@code false}
	 * @param addressType   Type of this address type
	 * @param desc          Description of this address type
	 * @param createdOn     A timestamp indicating when this address type was
	 *                      created
	 * @param lastUpdatedOn A timestamp indicating when this address type was last
	 *                      updated
	 */
	public AddressType(long id, long ownerId, boolean isOwnerOrg, String addressType, String desc, long createdOn,
			long lastUpdatedOn) {
		super(ownerId, createdOn, lastUpdatedOn);
		this.id = id;
		this.isOwnerOrg = isOwnerOrg;
		this.addressType = addressType;
		this.desc = desc;
		this.createdOn = createdOn;
		this.lastUpdatedOn = lastUpdatedOn;
	}

	/**
	 * To get the ID of this instance
	 * 
	 * @return {@code id} of this instance
	 */
	public long getId() {
		return id;
	}

	/**
	 * To set the ID of this instance.
	 * <p>
	 * The {@code id} being <i>primary key</i> of entities, it should, ideally, be
	 * set by the DB system on successful creation of the respective record.
	 * </p>
	 * 
	 * @param id ID of this instance
	 */
	public void setId(long id) {
		this.id = id;
	}

	/**
	 * To check if the owner of this instance represented by {@code ownerId} is an
	 * organization or not.
	 * 
	 * @return {@code true}, if the owner of this instance represented by
	 *         {@code ownerId} is an organization; otherwise, {@code false}
	 */
	@JsonProperty(value = "isOwnerOrg")
	public boolean isOwnerOrg() {
		return isOwnerOrg;
	}

	/**
	 * To set a {@code boolean} indicating whether the owner of this instance
	 * represented by {@code ownerId} is an organization or not.
	 * 
	 * @param isOwnerOrg Set to {@code true}, if the owner of this instance
	 *                   represented by {@code ownerId} is an organization;
	 *                   otherwise, {@code false}
	 */
	public void setOwnerOrg(boolean isOwnerOrg) {
		this.isOwnerOrg = isOwnerOrg;
	}

	/**
	 * To get the address type
	 * 
	 * @return {@code addressType} value
	 */
	public String getAddressType() {
		return addressType;
	}

	/**
	 * To set a address type
	 * 
	 * @param addressType An address type
	 */
	public void setAddressType(String addressType) {
		this.addressType = addressType;
	}

	/**
	 * To get the description of this address type
	 * 
	 * @return {@code desc} value
	 */
	public String getDesc() {
		return desc;
	}

	/**
	 * To set the description of this address type
	 * 
	 * @param desc Description of this address type
	 */
	public void setDesc(String desc) {
		this.desc = desc;
	}
}
