package in.co.mark.webservices.contacts.domain.model;

import in.co.mark.common.domain.model.OwnerSpecificModelBase;
import in.co.mark.common.persistence.util.EntityActiveStatus;

public class ContactIdentifier extends OwnerSpecificModelBase {
	/**
	 * The <i>primary key</i> of this entity. It will be generated by the DB system
	 * on successful creation of the respective record.
	 */
	private long id;
	private long contactId;
	private long identifierTypeId;
	private String identifierValue;
	private String desc;
	/**
	 * Location at which this identifier was issued
	 */
	private String issueLocation;
	/**
	 * Date when this identifier was issued
	 */
	private long issueDate;
	/**
	 * Date when this identifier expires
	 */
	private long expiryDate;
	private EntityActiveStatus status;

	/**
	 * Default constructor
	 */
	public ContactIdentifier() {

	}

	/**
	 * Initializes {@code contactId}, {@code identifierTypeId},
	 * {@code identifierNumber}, and {@code desc} properties of this instance
	 * 
	 * @param ownerId          ID of the owner of this instance
	 * @param contactId        ID of the contact to which this identifier is
	 *                         associated to
	 * @param identifierTypeId ID of the {@link IdentifierType}
	 * @param identifierValue  Identifier value like PAN or AADHAR number
	 * @param desc             Description of this identifier
	 */
	public ContactIdentifier(long ownerId, long contactId, long identifierTypeId, String identifierValue, String desc) {
		super(ownerId);
		this.contactId = contactId;
		this.identifierTypeId = identifierTypeId;
		this.identifierValue = identifierValue;
		this.desc = desc;
	}

	/**
	 * Initializes {@code contactId}, {@code identifierTypeId},
	 * {@code identifierNumber}, {@code desc}, {@code issueLocation},
	 * {@code issueDate}, and {@code expiryDate} properties of this instance
	 * 
	 * @param ownerId          ID of the owner of this instance
	 * @param contactId        ID of the contact to which this identifier is
	 *                         associated to
	 * @param identifierTypeId ID of the {@link IdentifierType}
	 * @param identifierValue  Identifier value like PAN or AADHAR number
	 * @param desc             Description of this identifier
	 * @param issueLocation    Location where this identifier was issued
	 * @param issueDate        Date when this identifier was issued
	 * @param expiryDate       Date when this identifier expires
	 */
	public ContactIdentifier(long ownerId, long contactId, long identifierTypeId, String identifierValue, String desc,
			String issueLocation, long issueDate, long expiryDate) {
		super(ownerId);
		this.contactId = contactId;
		this.identifierTypeId = identifierTypeId;
		this.identifierValue = identifierValue;
		this.desc = desc;
		this.issueLocation = issueLocation;
		this.issueDate = issueDate;
		this.expiryDate = expiryDate;
	}

	/**
	 * Initializes all properties of this instance
	 * 
	 * @param id               DB ID of this instance
	 * @param ownerId          ID of the owner of this instance
	 * @param contactId        ID of the contact to which this identifier is
	 *                         associated to
	 * @param identifierTypeId ID of the {@link IdentifierType}
	 * @param identifierValue  Identifier value like PAN or AADHAR number
	 * @param desc             Description of this identifier
	 * @param issueLocation    Location where this identifier was issued
	 * @param issueDate        Date when this identifier was issued
	 * @param expiryDate       Date when this identifier expires
	 * @param status           Active status of this record
	 * @param createdOn        A timestamp indicating when the respective DB record
	 *                         was created
	 * @param lastUpdatedOn    A timestamp indicating when the respective DB record
	 *                         was last updated
	 */
	public ContactIdentifier(long id, long ownerId, long contactId, long identifierTypeId, String identifierValue,
			String desc, String issueLocation, long issueDate, long expiryDate, EntityActiveStatus status,
			long createdOn, long lastUpdatedOn) {
		super(ownerId, createdOn, lastUpdatedOn);
		this.id = id;
		this.contactId = contactId;
		this.identifierTypeId = identifierTypeId;
		this.identifierValue = identifierValue;
		this.desc = desc;
		this.issueLocation = issueLocation;
		this.issueDate = issueDate;
		this.expiryDate = expiryDate;
		this.status = status;
	}

	/**
	 * To get the ID of this instance
	 * 
	 * @return {@code id} of this instance
	 */
	public long getId() {
		return id;
	}

	/**
	 * To set the ID of this instance.
	 * <p>
	 * The {@code id} being <i>primary key</i> of entities, it should, ideally, be
	 * set by the DB system on successful creation of the respective record.
	 * </p>
	 * 
	 * @param id ID of this instance
	 */
	public void setId(long id) {
		this.id = id;
	}

	/**
	 * To get the ID of the associated contact
	 * 
	 * @return {@code contactId} value
	 */
	public long getContactId() {
		return contactId;
	}

	/**
	 * To set the ID of the associated contact
	 * 
	 * @param contactId ID of a contact to associate to
	 */
	public void setContactId(long contactId) {
		this.contactId = contactId;
	}

	/**
	 * To get the identifier type ID
	 * 
	 * @return {@code identifierTypeId} value
	 */
	public long getIdentifierTypeId() {
		return identifierTypeId;
	}

	/**
	 * To set an Identifier type ID
	 * 
	 * @param dentifierTypeId Identifier type ID
	 */
	public void setIdentifierTypeId(long identifierTypeId) {
		this.identifierTypeId = identifierTypeId;
	}

	/**
	 * To get the identifier value
	 * 
	 * @return {@code identifierValue}
	 */
	public String getIdentifierValue() {
		return identifierValue;
	}

	/**
	 * To set an identifier value
	 * 
	 * @param identifierValue An identifier value
	 */
	public void setIdentifierValue(String identifierValue) {
		this.identifierValue = identifierValue;
	}

	/**
	 * To get the description of this identifier type
	 * 
	 * @return {@code desc} value
	 */
	public String getDesc() {
		return desc;
	}

	/**
	 * To set the description of this identifier type
	 * 
	 * @param desc Description of this identifier type
	 */
	public void setDesc(String desc) {
		this.desc = desc;
	}

	/**
	 * To get the location where this identifier was issued
	 * 
	 * @return {@code issueLocation} value
	 */
	public String getIssueLocation() {
		return issueLocation;
	}

	/**
	 * To set the location where this identifier was issued
	 * 
	 * @param issueLocation Location where this identifier was issued
	 */
	public void setIssueLocation(String issueLocation) {
		this.issueLocation = issueLocation;
	}

	/**
	 * To get the issue date of this identifier
	 * 
	 * @return {@code issueDate} value
	 */
	public long getIssueDate() {
		return issueDate;
	}

	/**
	 * To set the issue date of this identifier
	 * 
	 * @param issueDate Issue date of this identifier
	 */
	public void setIssueDate(long issueDate) {
		this.issueDate = issueDate;
	}

	/**
	 * To get the expiry-date of this identifier
	 * 
	 * @return {@code expiryDate} value
	 */
	public long getExpiryDate() {
		return expiryDate;
	}

	/**
	 * To set the expiry-date of this identifier
	 * 
	 * @param expiryDate Expiry-date of this identifier
	 */
	public void setExpiryDate(long expiryDate) {
		this.expiryDate = expiryDate;
	}

	/**
	 * To get the active status of this record
	 * 
	 * @return {@code status} value
	 */
	public EntityActiveStatus getStatus() {
		return status;
	}

	/**
	 * To set the active status of this record
	 * 
	 * @param status {@link EntityActiveStatus} indicating the active status of this
	 *               record
	 */
	public void setStatus(EntityActiveStatus status) {
		this.status = status;
	}
}
