package in.co.mark.webservices.contacts.domain.model;

import in.co.mark.common.domain.model.OwnerSpecificModelBase;
import in.co.mark.common.persistence.util.EntityActiveStatus;

/**
 * Represents an email address of a contact
 */
public class ContactEmail extends OwnerSpecificModelBase {
	/**
	 * The <i>primary key</i> of this entity. It will be generated by the DB system
	 * on successful creation of the respective record.
	 */
	private long id;
	private long emailTypeId;
	private String emailAddress;
	private EntityActiveStatus status;

	/**
	 * Default constructor
	 */
	public ContactEmail() {

	}

	/**
	 * Initializes {@code ownerUserId}, {@code emailType}, and {@code desc}
	 * properties of this instance
	 * 
	 * @param ownerUserId  ID of the owner user
	 * @param emailTypeId  Email type ID
	 * @param emailAddress Email type value of this instance
	 */
	public ContactEmail(long ownerUserId, long emailTypeId, String emailAddress) {
		super(ownerUserId);
		this.emailTypeId = emailTypeId;
		this.emailAddress = emailAddress;
	}

	/**
	 * Initializes all properties of this instance
	 * 
	 * @param id            DB ID of this instance
	 * @param ownerUserId   ID of the owner user
	 * @param emailTypeId   Email type ID
	 * @param emailAddress  Email type value of this instance
	 * @param status        Active status of this record
	 * @param createdOn     A timestamp indicating when the respective DB record was
	 *                      created
	 * @param lastUpdatedOn A timestamp indicating when the respective DB record was
	 *                      last updated
	 */
	public ContactEmail(long id, long ownerUserId, long emailTypeId, String emailAddress, EntityActiveStatus status,
			long createdOn, long lastUpdatedOn) {
		super(ownerUserId, createdOn, lastUpdatedOn);
		this.id = id;
		this.emailTypeId = emailTypeId;
		this.emailAddress = emailAddress;
		this.status = status;
	}

	/**
	 * To get the ID of this instance
	 * 
	 * @return {@code id} of this instance
	 */
	public long getId() {
		return id;
	}

	/**
	 * To set the ID of this instance.
	 * <p>
	 * The {@code id} being <i>primary key</i> of entities, it should, ideally, be
	 * set by the DB system on successful creation of the respective record.
	 * </p>
	 * 
	 * @param id ID of this instance
	 */
	public void setId(long id) {
		this.id = id;
	}

	/**
	 * To get the email type ID
	 * 
	 * @return {@code emailTypeId} value
	 */
	public long getEmailTypeId() {
		return emailTypeId;
	}

	/**
	 * To set an email type ID
	 * 
	 * @param emailTypeId Email type ID
	 */
	public void setEmailTypeId(long emailTypeId) {
		this.emailTypeId = emailTypeId;
	}

	/**
	 * To get the email address
	 * 
	 * @return {@code emailAddress} value
	 */
	public String getEmailAddress() {
		return emailAddress;
	}

	/**
	 * To set an email address
	 * 
	 * @param emailAddress An email address
	 */
	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	/**
	 * To get the active status of this record
	 * 
	 * @return {@code status} value
	 */
	public EntityActiveStatus getStatus() {
		return status;
	}

	/**
	 * To set the active status of this record
	 * 
	 * @param status {@link EntityActiveStatus} indicating the active status of this
	 *               record
	 */
	public void setStatus(EntityActiveStatus status) {
		this.status = status;
	}
}
