package in.co.mark.webservices.contacts.domain.model;

import in.co.mark.common.domain.model.OwnerSpecificModelBase;

/**
 * Represent an identifier type like AADHAR, PAN, etc.
 * <p>
 * Since an identifier type must be defined at organization level, the property
 * {@code ownerId}, inherited from class {@link OwnerSpecificModelBase}, will
 * always point to the organization.
 * </p>
 */
public class IdentifierType extends OwnerSpecificModelBase {
	/**
	 * The <i>primary key</i> of this entity. It will be generated by the DB system
	 * on successful creation of the respective record.
	 */
	private long id;
	private String identifierType;
	private String desc;

	/**
	 * Default constructor
	 */
	public IdentifierType() {

	}

	/**
	 * Initializes {@code ownerId}, {@code identifierType}, and {@code desc}
	 * properties of this instance
	 * 
	 * @param ownerId        ID of the owner - can be a user or an organization
	 * @param identifierType Identifier type name
	 * @param desc           Description of this identifier type
	 */
	public IdentifierType(long ownerId, String identifierType, String desc) {
		super(ownerId);
		this.identifierType = identifierType;
		this.desc = desc;
	}

	/**
	 * Initializes all properties of this instance
	 * 
	 * @param id             DB ID of this instance
	 * @param ownerId        ID of the owner - can be a user or an organization
	 * @param identifierType Identifier type name
	 * @param desc           Description of this identifier type
	 * @param createdOn      A timestamp indicating when the respective DB record
	 *                       was created
	 * @param lastUpdatedOn  A timestamp indicating when the respective DB record
	 *                       was last updated
	 */
	public IdentifierType(long id, long ownerId, String identifierType, String desc, long createdOn,
			long lastUpdatedOn) {
		super(ownerId, createdOn, lastUpdatedOn);
		this.id = id;
		this.identifierType = identifierType;
		this.desc = desc;
	}

	/**
	 * To get the ID of this instance
	 * 
	 * @return {@code id} of this instance
	 */
	public long getId() {
		return id;
	}

	/**
	 * To set the ID of this instance.
	 * <p>
	 * The {@code id} being <i>primary key</i> of entities, it should, ideally, be
	 * set by the DB system on successful creation of the respective record.
	 * </p>
	 * 
	 * @param id ID of this instance
	 */
	public void setId(long id) {
		this.id = id;
	}

	/**
	 * To get the identifier type value
	 * 
	 * @return {@code identifierType} value
	 */
	public String getIdentifierType() {
		return identifierType;
	}

	/**
	 * To set an identifier type value
	 * 
	 * @param identifierType An identifier type value
	 */
	public void setIdentifierType(String identifierType) {
		this.identifierType = identifierType;
	}

	/**
	 * To get the description of this identifier type
	 * 
	 * @return {@code desc} value
	 */
	public String getDesc() {
		return desc;
	}

	/**
	 * To set the description of this identifier type
	 * 
	 * @param desc Description of this identifier type
	 */
	public void setDesc(String desc) {
		this.desc = desc;
	}
}
