package in.co.mark.webservices.contacts.domain.model;

import in.co.mark.common.domain.model.UserSpecificModel;

public class NamePrefix extends UserSpecificModel {
	/**
	 * The <i>primary key</i> of this entity. It will be generated by the DB system
	 * on successful creation of the respective record.
	 */
	private int id;
	private String namePrefix;
	private String desc;

	/**
	 * Initializes {@code ownerUserId}, {@code namePrefix}, and {@code desc}
	 * properties of this instance
	 * 
	 * @param ownerUserId ID of the owner user
	 * @param namePrefix  Name prefix value of this instance
	 * @param desc        Description of this name prefix
	 */
	public NamePrefix(long ownerUserId, String namePrefix, String desc) {
		super(ownerUserId);
		this.namePrefix = namePrefix;
		this.desc = desc;
	}

	/**
	 * Initializes all properties of this instance
	 * 
	 * @param id            DB ID of this instance
	 * @param ownerUserId   ID of the owner user
	 * @param namePrefix    Name prefix value of this instance
	 * @param desc          Description of this name prefix
	 * @param createdOn     A timestamp indicating when the respective DB record was
	 *                      created
	 * @param lastUpdatedOn A timestamp indicating when the respective DB record was
	 *                      last updated
	 */
	public NamePrefix(int id, long ownerUserId, String namePrefix, String desc, long createdOn, long lastUpdatedOn) {
		super(ownerUserId, createdOn, lastUpdatedOn);
		this.id = id;
		this.namePrefix = namePrefix;
		this.desc = desc;
	}

	/**
	 * To get the ID of this instance
	 * 
	 * @return {@code id} of this instance
	 */
	public int getId() {
		return id;
	}

	/**
	 * To set the ID of this instance.
	 * <p>
	 * The {@code id} being <i>primary key</i> of entities, it should, ideally, be
	 * set by the DB system on successful creation of the respective record.
	 * </p>
	 * 
	 * @param id ID of this instance
	 */
	public void setId(int id) {
		this.id = id;
	}

	/**
	 * To get the name prefix value
	 * 
	 * @return {@code namePrefix} value
	 */
	public String getNamePrefix() {
		return namePrefix;
	}

	/**
	 * To set a name prefix value
	 * 
	 * @param namePrefix A name prefix value
	 */
	public void setNamePrefix(String namePrefix) {
		this.namePrefix = namePrefix;
	}

	/**
	 * To get the description of this name prefix
	 * 
	 * @return {@code desc} value
	 */
	public String getDesc() {
		return desc;
	}

	/**
	 * To set the description of this name prefix
	 * 
	 * @param desc Description of this name prefix
	 */
	public void setDesc(String desc) {
		this.desc = desc;
	}
}
